spring:
  datasource:
    url: jdbc:sqlite:StoreDB.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: com.damazon.config.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: none	  

server:
  servlet:
    context-path: /Damazon

app:
  jwtSecret: "bXlKV1RTZWNyZXRLZXkxMjMh"  # Unpredictable key :O wow
  jwtExpirationInMs: 604800000  # Token Expiration: One week (in milliseconds)

